apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alert-hub-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/ifrcgo
    chart: ifrcgo-alert-hub-helm
    targetRevision: 0.0.1-develop.c53f7d29
    helm:
      valuesObject:
        global:
          security:
            allowInsecureImages: true
        redis:
          image:
            repository: bitnamilegacy/redis
        # NOTE: This should be adjusted in future to a value optimized for the workload
        # Vertical Pod Autoscaler should be used for establishing these values:
        # https://learn.microsoft.com/en-us/azure/aks/vertical-pod-autoscaler
        api:
          resources:
            requests:
              cpu: "0.2"
              memory: 1Gi
        worker:
          beat:
            resources:
              requests:
                cpu: "0.1"
                memory: 0.2Gi
          flower:
            resources:
              requests:
                cpu: "0.1"
                memory: 0.5Gi
          queues:
            default:
              resources:
                requests:
                  cpu: "0.1"
                  memory: 0.5Gi
            feeds:
              resources:
                requests:
                  cpu: "0.1"
                  memory: 0.5Gi
        ingress:
          host: "alerthub-api.ifrc.org"
          tls:
            secretName: "alerthub-helm-secret-cert"
        azure:
          aksSecretsProviderAvailable: true
          keyvault:
            name: "alert-hub-production-kv"
            clientId: "5853dc85-0d06-4f6d-9145-c72680a65ad9"
            tenantId: "a2b53be5-734e-4e6c-ab0d-d184f60fd917"
        env:
          APP_FRONTEND_HOST: "https://alerthub.ifrc.org"
          APP_DOMAIN: "alerthub-api.ifrc.org"
          DJANGO_ALLOWED_HOSTS: "alerthub-api.ifrc.org"
          SESSION_COOKIE_DOMAIN: ".ifrc.org"
          CSRF_COOKIE_DOMAIN: ".ifrc.org"
          CORS_ALLOWED_ORIGINS: "https://alerthub.ifrc.org"
          # Blob Storage Configs
          USE_AZURE_STORAGE: true
          AZURE_CLIENT_ID: 5853dc85-0d06-4f6d-9145-c72680a65ad9
          AZURE_TENANT_ID: a2b53be5-734e-4e6c-ab0d-d184f60fd917
          AZURE_STORAGE_MEDIA_CONTAINER: alert-hub-production-media-container
          AZURE_STORAGE_STATIC_CONTAINER: alert-hub-production-static-container
          AZURE_STORAGE_ACCOUNT_NAME: ifrcpgo
          AZURE_STORAGE_MANAGED_IDENTITY: true
        serviceAccount:
          create: true
          name: service-token-reader
          annotations:
            azure.workload.identity/client-id: "5853dc85-0d06-4f6d-9145-c72680a65ad9"
          labels:
            azure.workload.identity/use: "true"
      valueFiles:
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: alert-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
