apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: montandon-eoapi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://devseed.com/eoapi-k8s/
  # - repoURL: https://github.com/developmentseed/eoapi-k8s.git
    chart: eoapi
    targetRevision: 0.8.1
    # targetRevision: "stac.overrideRootPath"
    # path: charts/eoapi
    helm:
      valuesObject:
        ingress:
          enabled: false
          # host: "montandon-eoapi-stage.ifrc.org"
          # tls:
          #   enabled: true
          #   secretName: montandon-eoapi-helm-secret-cert
          # annotations:
          #   # increase the max body size to 100MB
          #   nginx.ingress.kubernetes.io/proxy-body-size: "100m"
          #   nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          #   nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
          #   nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
        raster:
          enabled: false
        stac:
          image:
            tag: 6.1.2
          overrideRootPath: ""
          settings:
            labels:
              azure.workload.identity/use: "true"
            resources:
              requests:
                memory: "2048Mi"
                cpu: "500m"
              limits:
                memory: "4096Mi"
                cpu: "1000m"
            envVars:
              ENABLE_TRANSACTIONS_EXTENSIONS: "TRUE"
              FORWARDED_ALLOW_IPS: "*"
              PROXY_HEADERS: True
              CORS_ORIGINS: "https://localhost:3000,https://alerthub.ifrc.org,https://montandon-eoapi.ifrc.org"
              CORS_ORIGIN_REGEX: ".*"
              CORS_HEADERS: "Accept, Authorization, Content-Type, Origin, X-Requested-With"
              CORS_METHODS: "GET,OPTIONS,POST"
              CORS_CREDENTIALS: "true"
            extraVolumeMounts:
              - name: azure-keyvault-secrets
                mountPath: /mnt/secrets-store
                readOnly: true
            extraVolumes:
              - name: azure-keyvault-secrets
                csi:
                  driver: secrets-store.csi.k8s.io
                  readOnly: true
                  volumeAttributes:
                    secretProviderClass: azure-secret-provider-montandon-eoapi
        vector:
          enabled: false

        serviceAccount:
          create: true
          automount: true
          annotations:
            azure.workload.identity/client-id : "8bf208ec-d73c-42d1-a4a9-817d2936a883"
          labels:
            azure.workload.identity/use: "true"

        pgstacBootstrap:
          enabled: true
          settings:
            # labels:
            #   azure.workload.identity/use: "true"
            # extraVolumes:
            #   - name: azure-keyvault-secrets
            #     csi:
            #       driver: secrets-store.csi.k8s.io
            #       readOnly: true
            #       volumeAttributes:
            #         secretProviderClass: azure-secret-provider-montandon-eoapi
            queryables:
              # configMap
              - name: "stac-queryables.json"
                configMapRef:
                  name: montandon-eoapi-stac-queryables
                  key: stac_queryables.json
                indexFields: ["monty:hazard_codes", "monty:country_codes", "roles"]
                deleteMissing: true
        postgresql:
          type: "external-secret"
          external:
            existingSecret:
              name: pgstac-secrets-montandon-eoapi
              keys:
                username: "DB_USER"
                password: "DB_PASSWORD"
                # Optional: if these are provided in the secret
                # Note: These values override external.host, external.port and external.database if defined
                host: "DB_HOST"
                database: "DB_NAME"
                port: "DB_PORT"

        postgrescluster:
          enabled: false

  - path: applications/argocd/production/applications/montandon-eoapi/
    targetRevision: master
    repoURL: https://github.com/IFRCGo/go-deploy.git
  - repoURL: https://github.com/developmentseed/stac-auth-proxy.git
    targetRevision: v0.9.2
    path: helm/
    helm:
      valuesObject:
        env:
          UPSTREAM_URL: "http://montandon-eoapi-stac:8080"
          # UPSTREAM_URL: "https://montandon-eoapi.ifrc.org/stac"
          OIDC_DISCOVERY_URL: "https://goadmin.ifrc.org/o/.well-known/openid-configuration"
          OVERRIDE_HOST: "0"
          ROOT_PATH: "/stac"
        ingress:
          enabled: "true"
          host: "montandon-eoapi.ifrc.org" # Decide on URL etc
          className: "nginx"
          tls:
            enabled: "true"
            secretName: "montandon-eoapi-helm-secret-cert"
        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: montandon-eoapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
