apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: montandon-eoapi-stats
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/ifrcgo/montandon-eoapi-stats
    chart: montandon-eoapi-stats-helm
    targetRevision: 0.2.5
    helm:
      valuesObject:
        ingress:
          enabled: true
          host: montandon-eoapi.ifrc.org
          path: /stats
  destination:
    server: https://kubernetes.default.svc
    namespace: montandon-eoapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
