apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alert-hub-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/ifrcgo
    chart: alert-hub-web-app-helm
    targetRevision: 0.0.1-develop.c6e6cec6
    helm:
      parameters:
        - name: app.ingress.hostname
          value: "alerthub-stage.ifrc.org"
        - name: app.ingress.host  # NOTE: Bug
          value: "alerthub-stage.ifrc.org"
        - name: app.ingress.ingressClassName
          value: nginx
        - name: app.ingress.tls.secretName
          value: "alerthub-helm-secret-cert"
        - name: app.env.APP_GRAPHQL_API_ENDPOINT
          value: https://alerthub-stage-api.ifrc.org/graphql/
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: alert-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
