apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alert-hub-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/ifrcgo/alert-hub-backend
    chart: ifrcgo-alert-hub-helm
    targetRevision: 0.0.1-develop.300568e
    helm:
      parameters:
        - name: ingress.host
          value: "alerthub-stage-api.ifrc.org"
        - name: ingress.tls.secretName
          value: "alerthub-helm-secret-cert"
        - name: azure.aksSecretsProviderAvailable
          value: "true"
        - name: azure.keyvault.name
          value: "alert-hub-staging-kv"
        - name: azure.keyvault.clientId
          value: "99dd63fe-721e-4abb-b30d-e2b782d2893d"
        - name: azure.keyvault.tenantId
          value: "a2b53be5-734e-4e6c-ab0d-d184f60fd917" 
        - name: env.APP_FRONTEND_HOST 
          value: "https://alerthub-stage.ifrc.org"
        - name: env.APP_DOMAIN 
          value: "alerthub-stage-api.ifrc.org"
        - name: env.DJANGO_ALLOWED_HOSTS 
          value: "alerthub-stage-api.ifrc.org"
        - name: env.SESSION_COOKIE_DOMAIN 
          value: ".ifrc.org"
        - name: env.CSRF_COOKIE_DOMAIN 
          value: ".ifrc.org"
        - name: env.CORS_ALLOWED_ORIGINS
          value: "https://alerthub-stage.ifrc.org"
      valueFiles:
        - values-staging.yaml
      values: |
        serviceAccount:
          create: true
          name: service-token-reader
          annotations:
            azure.workload.identity/client-id: "99dd63fe-721e-4abb-b30d-e2b782d2893d"
          labels:
            azure.workload.identity/use: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: alert-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true