apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alert-hub-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/ifrcgo/alert-hub-backend
    chart: ifrcgo-alert-hub-helm
    targetRevision: 0.0.1-develop.4bceb7d
    helm:
      valuesObject:
        ingress:
          host: "alerthub-stage-api.ifrc.org"
          tls:
            secretName: "alerthub-helm-secret-cert"
        azure:
          aksSecretsProviderAvailable: true
          keyvault:
            name: "alert-hub-staging-kv"
            clientId: "99dd63fe-721e-4abb-b30d-e2b782d2893d" 
            tenantId: "a2b53be5-734e-4e6c-ab0d-d184f60fd917"
        env:
          APP_FRONTEND_HOST: "https://alerthub-stage.ifrc.org"
          APP_DOMAIN: "alerthub-stage-api.ifrc.org"
          DJANGO_ALLOWED_HOSTS: "alerthub-stage-api.ifrc.org"
          SESSION_COOKIE_DOMAIN: ".ifrc.org"
          CSRF_COOKIE_DOMAIN: ".ifrc.org"
          CORS_ALLOWED_ORIGINS: "https://alerthub-stage.ifrc.org"
          # Blob Storage Configs
          USE_AZURE_STORAGE: True
          AZURE_STORAGE_MEDIA_CONTAINER: alert-hub-staging-media-container
          AZURE_STORAGE_STATIC_CONTAINER: alert-hub-staging-static-container
          AZURE_STORAGE_ACCOUNT_NAME: ifrctgo
          AZURE_STORAGE_MANAGED_IDENTITY: True
          AZURE_STORAGE_TOKEN_CREDENTIAL: None
        serviceAccount:
          create: true
          name: service-token-reader
          annotations:
            azure.workload.identity/client-id: "99dd63fe-721e-4abb-b30d-e2b782d2893d"
          labels:
            azure.workload.identity/use: "true"
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: alert-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true