apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cacheppuccino
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/ifrcgo
    chart: cacheppuccino-helm
    targetRevision: 0.1.0-7e61229
    helm:
      valueFiles:
        - values/go-deploy.yaml
        - values/staging.yaml
      valuesObject:
        fullnameOverride: ifrcgo-cacheppuccino
        ingress:
          className: nginx
          host: cacheppuccino-stage.ifrc.org
          tls:
            secretName: cacheppuccino-helm-secret-cert
        sqlite:
          pvc:
            size: 512Mi
        serviceAccount:
          annotations:
            azure.workload.identity/client-id: "f39be471-33b8-4a7b-ae8b-e156427a6589"
        secretsStoreCsiDriver:
          parameters:
            clientID: "f39be471-33b8-4a7b-ae8b-e156427a6589"
            keyvaultName: "cacheppuccino-staging-kv"
            tenantId: "a2b53be5-734e-4e6c-ab0d-d184f60fd917"
  destination:
    server: https://kubernetes.default.svc
    namespace: cacheppuccino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
