apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cacheppuccino
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/ifrcgo
    chart: cacheppuccino-helm
    targetRevision: 0.1.0-b413077
    helm:
      valueFiles:
        - values/go-deploy.yaml
      valuesObject:
        fullnameOverride: ifrcgo-cacheppuccino
        ingress:
          host: cacheppuccino-stage.ifrc.org
          tls:
            secretName: cacheppuccino-helm-secret-cert
        sqlite:
          pvc:
            size: 512Mi
        serviceAccount:
          annotations:
            # TODO(susilnem): update this after resource has been created.
            azure.workload.identity/client-id: ""
        # TODO(susilnem): update this after resource has been created.
        secretsStoreCsiDriver:
          parameters:
            clientID: ""
            keyvaultName: ""
            tenantId: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: cacheppuccino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
