apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: montandon-eoapi-pgo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: registry.developers.crunchydata.com/crunchydata
    chart: pgo
    targetRevision: 5.5.2
    helm:
      valuesObject:
        disable_check_for_upgrades: true
  destination:
    server: https://kubernetes.default.svc
    namespace: montandon-eoapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
