apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: montandon-eoapi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://devseed.com/eoapi-k8s/
  # - repoURL: https://github.com/developmentseed/eoapi-k8s.git
    chart: eoapi
    targetRevision: 0.7.5
    # targetRevision: feature/azure-secrets
    path: helm-chart/eoapi
    helm:
      valuesObject:
        ingress:
          host: "montandon-eoapi-stage.ifrc.org"
          tls:
            enabled: true
            secretName: montandon-eoapi-helm-secret-cert
          annotations:
            # increase the max body size to 100MB
            nginx.ingress.kubernetes.io/proxy-body-size: "100m"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
        raster:
          enabled: false
        stac:
          # image:
          #   name: ghcr.io/sunu/stac-fastapi-pgstac
          #   tag: 5.0.0-test7
          settings:
            labels:
              azure.workload.identity/use: "true"
            extraEnvVars:
              FORWARDED_ALLOW_IPS: "*"
              PROXY_HEADERS: True
              POSTGRES_USER: postgres
              POSTGRES_PORT: 5432
            # extraEnvFrom:
            #   - secretRef:
            #       name: pgstac-secrets-montandon-eoapi
            extraVolumeMounts:
              - name: azure-keyvault-secrets
                mountPath: /mnt/secrets-store
                readOnly: true
            extraVolumes:
              - name: azure-keyvault-secrets
                csi:
                  driver: secrets-store.csi.k8s.io
                  readOnly: true
                  volumeAttributes:
                    secretProviderClass: azure-secret-provider-montandon-eoapi
        vector:
          enabled: false

        serviceAccount:
          create: true
          automount: true
          annotations:
            azure.workload.identity/client-id : "9b1f12a8-4ae9-4281-afa9-948451f77dce"
          labels:
            azure.workload.identity/use: "true"

        pgstacBootstrap:
          enabled: false
          # image:
          #   name: ghcr.io/stac-utils/pgstac
          #   tag: v0.9.5
          settings:
            labels:
              azure.workload.identity/use: "true"
            extraEnvVars:
              POSTGRES_USER: postgres
              POSTGRES_PORT: 5432
            # extraEnvFrom:
            #   - secretRef:
            #       name: pgstac-secrets-montandon-eoapi
            extraVolumes:
              - name: azure-keyvault-secrets
                csi:
                  driver: secrets-store.csi.k8s.io
                  readOnly: true
                  volumeAttributes:
                    secretProviderClass: azure-secret-provider-montandon-eoapi
        postgresql:
          type: "external-secret"
          external:
            existingSecret:
              name: pgstac-secrets-montandon-eoapi
              keys:
                username: "DB_USER"
                password: "DB_PASSWORD"
                # Optional: if these are provided in the secret
                # Note: These values override external.host, external.port and external.database if defined
                host: "DB_HOST"
                database: "DB_NAME"
                port: "DB_PORT"
        
        postgrescluster:
          enabled: false
          # instances:
          # - name: eoapi
          #   replicas: 1
          #   dataVolumeClaimSpec:
          #     accessModes:
          #     - "ReadWriteOnce"
          #     resources:
          #       requests:
          #         storage: "600Gi"
          #         cpu: "1024m"
          #         memory: "3048Mi"
  - path: applications/argocd/staging/applications/montndon-eoapi/
    targetRevision: develop
    repoURL: https://github.com/IFRCGo/go-deploy.git
  - repoURL: https://github.com/developmentseed/stac-auth-proxy.git
    targetRevision: v0.9.2
    path: helm/
    helm:
      valuesObject:
        env:
          UPSTREAM_URL: "http://stac-montandon-eoapi.montandon-eoapi.svc.cluster.local"
          OIDC_DISCOVERY_URL: "https://goadmin-stage.ifrc.org/o/.well-known/openid-configuration"
        ingress:
          enabled: "true"
          host: "stac-test.whydidweevendothis.com"
          className: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod-issuer"
          tls:
            enabled: "true"
            secretName: "stac-auth-proxy-tls-cert"
        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: montandon-eoapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
