apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: montandon-etl
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/ifrcgo/montandon-etl
    chart: montandon-etl-helm
    targetRevision: 0.1.1-develop.c6217338
    helm:
      valueFiles:
        - values/operators.yaml
        - values/go-deploy.yaml
        - values/staging.yaml
      valuesObject:
        app:
          ingress:
            host: montandon-etl-stage.ifrc.org
            tls:
              secretName: montandon-helm-secret-cert
          env:
            # Azure configs
            AZURE_STORAGE_ENABLE: "true"
            AZURE_STORAGE_ACCOUNT_NAME: montystaging6757
            AZURE_STORAGE_MEDIA_CONTAINER: montandon-etl-staging-media-container
            AZURE_STORAGE_STATIC_CONTAINER: montandon-etl-staging-static-container
            # ETL Load config
            EOAPI_DOMAIN: "montandon-eoapi-stage.ifrc.org"
          serviceAccount:
            annotations:
              azure.workload.identity/client-id : "bcc2593b-4885-46b4-8430-b85b34a22737"
          secretsStoreCsiDriver:
            parameters:
              clientID: "bcc2593b-4885-46b4-8430-b85b34a22737"
              keyvaultName: "montandon-etl-staging-kv"
              tenantId: "a2b53be5-734e-4e6c-ab0d-d184f60fd917"
  destination:
    server: https://kubernetes.default.svc
    namespace: montandon-etl
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
