apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: montandon-eoapi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://devseed.com/eoapi-k8s/
    chart: eoapi
    targetRevision: 0.5.0
    helm:
      valuesObject:
        ingress:
          host: "montandon-eoapi-stage.ifrc.org"
          tls:
            enabled: false
        pgstacBootstrap:
          settings:
            envVars:
              LOAD_FIXTURES: "0"
              RUN_FOREVER: "1"
        postgrescluster:
          instances:
          - name: eoapi
            replicas: 1
            dataVolumeClaimSpec:
              accessModes:
              - "ReadWriteOnce"
              resources:
                requests:
                  storage: "600Gi"
                  cpu: "1024m"
                  memory: "3048Mi"

  destination:
    server: https://kubernetes.default.svc
    namespace: montandon-eoapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
