apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sdt-staging-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ifrcgostagingcontainerregistry.azurecr.io/ifrcgo/sdt-api
    chart: ifrcgo-sdt-helm
    targetRevision: 0.0.1-develop.c32f3671  # Update "Survey Design Tool" to "IFRC Survey Designer"
    helm:
      valuesObject:
        fullnameOverride: ifrcgo-sdt-staging
        environment: STAGING
        ingress:
          enabled: true
          host: sdt-staging-api.ifrc.org
          className: nginx
          tls:
            enabled: true
            secretName: sdt-helm-secret-cert
        env:
          BASE_DOMAIN: https://sdt-staging-api.ifrc.org
          FRONTEND_BASE_DOMAIN: https://sdt-staging.ifrc.org
          ALLOWED_HOSTS: "sdt-staging-api.ifrc.org"
          SESSION_COOKIE_DOMAIN: ".ifrc.org"
          CSRF_COOKIE_DOMAIN: ".ifrc.org"
          EMAIL_FROM: ''  # TODO: Update this
          USE_AZURE_STORAGE: "true"
          AZURE_STORAGE_MEDIA_CONTAINER: sdt-staging-media-container
          AZURE_STORAGE_STATIC_CONTAINER: sdt-staging-static-container
          AZURE_STORAGE_ACCOUNT_NAME: sdtstaging2813
          AZURE_STORAGE_MANAGED_IDENTITY: true
        # Azure related configurations
        azure:
          aksSecretsProviderAvailable: true
          keyvault:
            name: "sdt-staging-kv"
            clientId: "3355b3c7-a6be-466a-83f4-19c5f67cc161"
            tenantId: "a2b53be5-734e-4e6c-ab0d-d184f60fd917"
        serviceAccount:
          # Specifies whether a service account should be created
          # Required when using workload identity to access Azure Key Vault Secrets
          create: true
          automount: true
          annotations:
            azure.workload.identity/client-id : "3355b3c7-a6be-466a-83f4-19c5f67cc161"
          labels:
            azure.workload.identity/use: "true"
          name: "service-token-reader"
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sdt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
