apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stac-auth-proxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/developmentseed/stac-auth-proxy/charts
    chart: stac-auth-proxy
    targetRevision: "*"
    helm:
      parameters:
        - name: env.UPSTREAM_URL
          value: "http://montandon-eoapi.montandon-eoapi.svc.cluster.local/stac"
        - name: env.OIDC_DISCOVERY_URL
          value: "https://goadmin-stage.ifrc.org/o/.well-known/openid-configuration"
        - name: ingress.enabled
          value: "true"
        - name: ingress.host
          value: "stac-test.whydidweevendothis.com"
        - name: ingress.className
          value: "nginx"
        - name: ingress.tls.enabled
          value: "true"
        - name: ingress.tls.secretName
          value: "stac-auth-proxy-helm-secret-cert"
        - name: replicaCount
          value: "1"
  destination:
    server: https://kubernetes.default.svc
    namespace: stac-auth-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true