trigger:
- develop
- master

# no PR triggers
pr: none

resources:
  repositories:
  - repository: go-deploy
    type: github
    endpoint: IFRCGo
    name: IFRCGo/go-deploy
    ref: ${{ variables['Build.SourceBranchName'] }}

pool:
  vmImage: ubuntu-latest

jobs:
- job: 'Deploy_GO_API'
  steps:
  - checkout: go-deploy
    displayName: "Checkout go-deploy"
    path: go-deploy

  # Deploy go-api to staging
  - script: chmod +x $(Pipeline.Workspace)/go-deploy/applications/go-api/scripts/deploy-go-api.sh
    displayName: "Make deployment script executable"

  - bash: $(Pipeline.Workspace)/go-deploy/applications/go-api/scripts/deploy-go-api.sh
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
    displayName: "Deploy staging instance of go-api"
    env:
      ENVIRONMENT: staging
      VERSION: "0.0.2-develop.c4c072d3"
      # For Azure CLI
      AZURE_TENANT_ID: $(TERRAFORM_TENANT_ID)
      AZURE_CLIENT_ID: $(TERRAFORM_SERVICE_PRINCIPAL_ID)
      AZURE_CLIENT_SECRET: $(TERRAFORM_SERVICE_PRINCIPAL_KEY)
      # Application settings
      API_FQDN: $(STAGING_ADMIN_URL)
      API_ADDITIONAL_FQDN: ''
      DJANGO_SECRET_KEY: $(STAGING_DJANGO_SECRET_KEY)
      DJANGO_DB_NAME: $(STAGING_DJANGO_DB_NAME)
      DJANGO_DB_USER: $(STAGING_DJANGO_DB_USER)
      DJANGO_DB_PASS: $(STAGING_DJANGO_DB_PASS)
      DJANGO_DB_HOST: $(STAGING_DJANGO_DB_HOST)
      DJANGO_DB_PORT: $(STAGING_DJANGO_DB_PORT)
      AZURE_STORAGE_KEY: $(STAGING_AZURE_STORAGE_KEY)
      AZURE_STORAGE_ACCOUNT: $(STAGING_AZURE_STORAGE_ACCOUNT)
      EMAIL_API_ENDPOINT: $(STAGING_EMAIL_API_ENDPOINT)
      EMAIL_HOST: $(STAGING_EMAIL_HOST)
      EMAIL_PORT: $(STAGING_EMAIL_PORT)
      EMAIL_USER: $(STAGING_EMAIL_USER)
      EMAIL_PASS: $(STAGING_EMAIL_PASS)
      TEST_EMAILS: $(STAGING_TEST_EMAILS)
      AWS_TRANSLATE_ACCESS_KEY: $(STAGING_AWS_TRANSLATE_ACCESS_KEY)
      AWS_TRANSLATE_SECRET_KEY: $(STAGING_AWS_TRANSLATE_SECRET_KEY)
      AWS_TRANSLATE_REGION: $(STAGING_AWS_TRANSLATE_REGION)
      CELERY_REDIS_URL: $(STAGING_CELERY_REDIS_URL)
      CACHE_MIDDLEWARE_SECONDS: $(STAGING_CACHE_MIDDLEWARE_SECONDS)
      MOLNIX_API_BASE: $(STAGING_MOLNIX_API_BASE)
      MOLNIX_USERNAME: $(STAGING_MOLNIX_USERNAME)
      MOLNIX_PASSWORD: $(STAGING_MOLNIX_PASSWORD)
      ERP_API_ENDPOINT: $(STAGING_ERP_API_ENDPOINT)
      ERP_API_SUBSCRIPTION_KEY: $(STAGING_ERP_API_SUBSCRIPTION_KEY)
      FDRS_APIKEY: $(STAGING_FDRS_APIKEY)
      FDRS_CREDENTIAL: $(STAGING_FDRS_CREDENTIAL)
      HPC_CREDENTIAL: $(STAGING_HPC_CREDENTIAL)
      APPLICATION_INSIGHTS_INSTRUMENTATION_KEY: $(STAGING_APPLICATION_INSIGHTS_INSTRUMENTATION_KEY)
      ELASTIC_SEARCH_HOST: $(STAGING_ELASTIC_SEARCH_HOST)
      GO_FTPHOST: $(STAGING_GO_FTPHOST)
      GO_FTPUSER: $(STAGING_GO_FTPUSER)
      GO_FTPPASS: $(STAGING_GO_FTPPASS)
      GO_DBPASS: $(STAGING_GO_DBPASS)
      APPEALS_USER: $(STAGING_APPEALS_USER)
      APPEALS_PASS: $(STAGING_APPEALS_PASS)
      FRONTEND_URL: $(STAGING_FRONTEND_URL)
      RESOURCES_DB_NAME: $(STAGING_RESOURCES_DB_NAME)
      RESOURCES_DB_SERVER: $(STAGING_RESOURCES_DB_SERVER)
      REGION: $(STAGING_REGION)
      SENTRY_DSN: $(STAGING_SENTRY_DSN)
      SENTRY_SAMPLE_RATE: $(STAGING_SENTRY_SAMPLE_RATE)
      DJANGO_READ_ONLY: $(STAGING_DJANGO_READ_ONLY)
      AUTO_TRANSLATION_TRANSLATOR: $(STAGING_AUTO_TRANSLATION_TRANSLATOR)
      IFRC_TRANSLATION_DOMAIN: $(STAGING_IFRC_TRANSLATION_DOMAIN)
      IFRC_TRANSLATION_HEADER_API_KEY: $(STAGING_IFRC_TRANSLATION_HEADER_API_KEY)
      DEBUG_EMAIL: ''
      DOCKER_HOST_IP: ''
      DJANGO_DEBUG: ''
      DJANGO_ADDITIONAL_ALLOWED_HOSTS: ''
      # TLS cert and key should be base64 encoded
      API_TLS_CRT: $(STAGING_API_TLS_CRT)
      API_TLS_KEY: $(STAGING_API_TLS_KEY)
      API_ADDITIONAL_DOMAIN_TLS_CRT: ''
      API_ADDITIONAL_DOMAIN_TLS_KEY: ''
      # Country page
      NS_CONTACT_USERNAME: $(STAGING_NS_CONTACT_USERNAME)
      NS_CONTACT_PASSWORD: $(STAGING_NS_CONTACT_PASSWORD)
      ACAPS_API_TOKEN: $(STAGING_ACAPS_API_TOKEN)
      NS_DOCUMENT_API_KEY: $(STAGING_NS_DOCUMENT_API_KEY)
      NS_INITIATIVES_API_KEY: $(STAGING_NS_INITIATIVES_API_KEY)
      NS_INITIATIVES_API_TOKEN: $(STAGING_NS_INITIATIVES_API_TOKEN)
      JWT_PRIVATE_KEY_BASE64_ENCODED: $(STAGING_JWT_PRIVATE_KEY_BASE64_ENCODED)
      JWT_PUBLIC_KEY_BASE64_ENCODED: $(STAGING_JWT_PUBLIC_KEY_BASE64_ENCODED)
      JWT_EXPIRE_TIMESTAMP_DAYS: $(STAGING_JWT_EXPIRE_TIMESTAMP_DAYS)
      AZURE_OPENAI_DEPLOYMENT_NAME: $(STAGING_AZURE_OPENAI_DEPLOYMENT_NAME)
      AZURE_OPENAI_ENDPOINT: $(STAGING_AZURE_OPENAI_ENDPOINT)
      AZURE_OPENAI_API_KEY: $(STAGING_AZURE_OPENAI_API_KEY)
      # OAUTH Toolkit
      OIDC_ENABLE: $(STAGING_OIDC_ENABLE)
      OIDC_RSA_PRIVATE_KEY_BASE64_ENCODED: $(STAGING_OIDC_RSA_PRIVATE_KEY_BASE64_ENCODED)
      OIDC_RSA_PUBLIC_KEY_BASE64_ENCODED: $(STAGING_OIDC_RSA_PUBLIC_KEY_BASE64_ENCODED)

  # Deploy go-api to production
  - bash: $(Pipeline.Workspace)/go-deploy/applications/go-api/scripts/deploy-go-api.sh
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    displayName: "Deploy production instance of go-api"
    env:
      ENVIRONMENT: production
      VERSION: "0.0.2-master.c939a4cd"
      # For Azure CLI
      AZURE_TENANT_ID: $(TERRAFORM_TENANT_ID)
      AZURE_CLIENT_ID: $(TERRAFORM_SERVICE_PRINCIPAL_ID)
      AZURE_CLIENT_SECRET: $(TERRAFORM_SERVICE_PRINCIPAL_KEY)
      # Production application settings
      API_FQDN: $(PRODUCTION_ADMIN_URL)
      API_ADDITIONAL_FQDN: $(PRODUCTION_ADDITIONAL_URL)
      DJANGO_SECRET_KEY: $(PRODUCTION_DJANGO_SECRET_KEY)
      DJANGO_DB_NAME: $(PRODUCTION_DJANGO_DB_NAME)
      DJANGO_DB_USER: $(PRODUCTION_DJANGO_DB_USER)
      DJANGO_DB_PASS: $(PRODUCTION_DJANGO_DB_PASS)
      DJANGO_DB_HOST: $(PRODUCTION_DJANGO_DB_HOST)
      DJANGO_DB_PORT: $(PRODUCTION_DJANGO_DB_PORT)
      AZURE_STORAGE_KEY: $(PRODUCTION_AZURE_STORAGE_KEY)
      AZURE_STORAGE_ACCOUNT: $(PRODUCTION_AZURE_STORAGE_ACCOUNT)
      EMAIL_API_ENDPOINT: $(PRODUCTION_EMAIL_API_ENDPOINT)
      EMAIL_HOST: $(PRODUCTION_EMAIL_HOST)
      EMAIL_PORT: $(PRODUCTION_EMAIL_PORT)
      EMAIL_USER: $(PRODUCTION_EMAIL_USER)
      EMAIL_PASS: $(PRODUCTION_EMAIL_PASS)
      TEST_EMAILS: $(PRODUCTION_TEST_EMAILS)
      AWS_TRANSLATE_ACCESS_KEY: $(PRODUCTION_AWS_TRANSLATE_ACCESS_KEY)
      AWS_TRANSLATE_SECRET_KEY: $(PRODUCTION_AWS_TRANSLATE_SECRET_KEY)
      AWS_TRANSLATE_REGION: $(PRODUCTION_AWS_TRANSLATE_REGION)
      CELERY_REDIS_URL: $(PRODUCTION_CELERY_REDIS_URL)
      CACHE_MIDDLEWARE_SECONDS: $(PRODUCTION_CACHE_MIDDLEWARE_SECONDS)
      MOLNIX_API_BASE: $(PRODUCTION_MOLNIX_API_BASE)
      MOLNIX_USERNAME: $(PRODUCTION_MOLNIX_USERNAME)
      MOLNIX_PASSWORD: $(PRODUCTION_MOLNIX_PASSWORD)
      ERP_API_ENDPOINT: $(PRODUCTION_ERP_API_ENDPOINT)
      ERP_API_SUBSCRIPTION_KEY: $(PRODUCTION_ERP_API_SUBSCRIPTION_KEY)
      FDRS_APIKEY: $(PRODUCTION_FDRS_APIKEY)
      FDRS_CREDENTIAL: $(PRODUCTION_FDRS_CREDENTIAL)
      HPC_CREDENTIAL: $(PRODUCTION_HPC_CREDENTIAL)
      APPLICATION_INSIGHTS_INSTRUMENTATION_KEY: $(PRODUCTION_APPLICATION_INSIGHTS_INSTRUMENTATION_KEY)
      ELASTIC_SEARCH_HOST: $(PRODUCTION_ELASTIC_SEARCH_HOST)
      GO_FTPHOST: $(PRODUCTION_GO_FTPHOST)
      GO_FTPUSER: $(PRODUCTION_GO_FTPUSER)
      GO_FTPPASS: $(PRODUCTION_GO_FTPPASS)
      GO_DBPASS: $(PRODUCTION_GO_DBPASS)
      APPEALS_USER: $(PRODUCTION_APPEALS_USER)
      APPEALS_PASS: $(PRODUCTION_APPEALS_PASS)
      FRONTEND_URL: $(PRODUCTION_FRONTEND_URL)
      RESOURCES_DB_NAME: $(PRODUCTION_RESOURCES_DB_NAME)
      RESOURCES_DB_SERVER: $(PRODUCTION_RESOURCES_DB_SERVER)
      REGION: $(PRODUCTION_REGION)
      SENTRY_DSN: $(PRODUCTION_SENTRY_DSN)
      SENTRY_SAMPLE_RATE: $(PRODUCTION_SENTRY_SAMPLE_RATE)
      DJANGO_READ_ONLY: $(PRODUCTION_DJANGO_READ_ONLY)
      AUTO_TRANSLATION_TRANSLATOR: $(PRODUCTION_AUTO_TRANSLATION_TRANSLATOR)
      IFRC_TRANSLATION_DOMAIN: $(PRODUCTION_IFRC_TRANSLATION_DOMAIN)
      IFRC_TRANSLATION_HEADER_API_KEY: $(PRODUCTION_IFRC_TRANSLATION_HEADER_API_KEY)
      DEBUG_EMAIL: ''
      DOCKER_HOST_IP: ''
      DJANGO_DEBUG: ''
      DJANGO_ADDITIONAL_ALLOWED_HOSTS: $(PRODUCTION_ADDITIONAL_URL)
      # TLS cert and key should be base64 encoded
      API_TLS_CRT: $(PRODUCTION_API_TLS_CRT)
      API_TLS_KEY: $(PRODUCTION_API_TLS_KEY)
      API_ADDITIONAL_DOMAIN_TLS_CRT: $(PRODUCTION_API_ADDITIONAL_DOMAIN_TLS_CRT)
      API_ADDITIONAL_DOMAIN_TLS_KEY: $(PRODUCTION_API_ADDITIONAL_DOMAIN_TLS_KEY)
      # Country page
      NS_CONTACT_USERNAME: $(PRODUCTION_NS_CONTACT_USERNAME)
      NS_CONTACT_PASSWORD: $(PRODUCTION_NS_CONTACT_PASSWORD)
      ACAPS_API_TOKEN: $(PRODUCTION_ACAPS_API_TOKEN)
      NS_DOCUMENT_API_KEY: $(PRODUCTION_NS_DOCUMENT_API_KEY)
      NS_INITIATIVES_API_KEY: $(PRODUCTION_NS_INITIATIVES_API_KEY)
      NS_INITIATIVES_API_TOKEN: $(PRODUCTION_NS_INITIATIVES_API_TOKEN)
      JWT_PRIVATE_KEY_BASE64_ENCODED: $(PRODUCTION_JWT_PRIVATE_KEY_BASE64_ENCODED)
      JWT_PUBLIC_KEY_BASE64_ENCODED: $(PRODUCTION_JWT_PUBLIC_KEY_BASE64_ENCODED)
      JWT_EXPIRE_TIMESTAMP_DAYS: $(PRODUCTION_JWT_EXPIRE_TIMESTAMP_DAYS)
      AZURE_OPENAI_DEPLOYMENT_NAME: $(PRODUCTION_AZURE_OPENAI_DEPLOYMENT_NAME)
      AZURE_OPENAI_ENDPOINT: $(PRODUCTION_AZURE_OPENAI_ENDPOINT)
      AZURE_OPENAI_API_KEY: $(PRODUCTION_AZURE_OPENAI_API_KEY)
      # OAUTH Toolkit
      OIDC_ENABLE: $(PRODUCTION_OIDC_ENABLE)
      OIDC_RSA_PRIVATE_KEY_BASE64_ENCODED: $(PRODUCTION_OIDC_RSA_PRIVATE_KEY_BASE64_ENCODED)
      OIDC_RSA_PUBLIC_KEY_BASE64_ENCODED: $(PRODUCTION_OIDC_RSA_PUBLIC_KEY_BASE64_ENCODED)

