name: Pre-commit checks

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  pre_commit_checks:
    name: Pre-Commit checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: hashicorp/setup-terraform@v3
      - uses: terraform-linters/setup-tflint@v4

      - uses: pre-commit/action@main
